//
// UntitledView.h
// Generated by Core Animator version 1.0 on 5/11/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface LWFAnimationArrowInventory : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// Grow
- (void)addGrowAnimation;
- (void)addGrowAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addGrowAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addGrowAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addGrowAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeGrowAnimation;

- (void)removeAllAnimations;

@end