# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Evil Cave' do
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'SplunkMint-iOS'
  pod 'pop', :git => 'https://github.com/facebook/pop.git'
  pod 'SpriteKit-Easing', :git => 'https://github.com/leonardowf/SpriteKit-Easing.git'
  pod 'ChartboostSDK'
end

target 'Evil CaveTests' do

end

